import { Inter } from "next/font/google";
import "./globals.css";
import AppHeader from "@/components/home-components/AppHeader";
import AppFooter from "@/components/home-components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
